### ISSUE TITLE
是否考虑统一中文版本？

### ISSUE THREAD

**Issue by jacty** [wangdoc/git-tutorial#2]
目前似乎繁体和简体中文混搭了，略微显得有点不太习惯。不知道是否有统一语言版本的打算？

**Comment by ruanyf** [comment]
这个仓库只用来存放资料，连草稿都算不上，不用看了。

目前没空，后面会写正式的 Git 教程。

**Comment by jacty** [comment]
那我克隆一个版本，我自己边看边修正吧。
